package com.wjz.springboot1.persistence.model;

import java.util.Date;

public class OrderPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.ID
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_no
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    private String orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.trade_id
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    private Integer tradeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.user_id
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.merchant_id
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    private String merchantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.merchant_name
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    private String merchantName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.ext_pay_order_no
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    private String extPayOrderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.ate_pay_order_no
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    private String atePayOrderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.pay_channel
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    private Integer payChannel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.pay_type
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    private Integer payType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.pay_time
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    private Date payTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.total_amount
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    private Long totalAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.payable_amount
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    private Long payableAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.paid_amount
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    private Long paidAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.merchant_discount_amount
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    private Long merchantDiscountAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.pay_discount_amount
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    private Long payDiscountAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.post_fee
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    private Long postFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.buyer_message
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    private String buyerMessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.seller_note
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    private String sellerNote;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.invoice_flag
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    private Integer invoiceFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.status
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.delete_flag
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    private Integer deleteFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.finish_time
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    private Date finishTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.CREATE_TIME
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.UPDATE_TIME
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.ID
     *
     * @return the value of t_order.ID
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.ID
     *
     * @param id the value for t_order.ID
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_no
     *
     * @return the value of t_order.order_no
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_no
     *
     * @param orderNo the value for t_order.order_no
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.trade_id
     *
     * @return the value of t_order.trade_id
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    public Integer getTradeId() {
        return tradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.trade_id
     *
     * @param tradeId the value for t_order.trade_id
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    public void setTradeId(Integer tradeId) {
        this.tradeId = tradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.user_id
     *
     * @return the value of t_order.user_id
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.user_id
     *
     * @param userId the value for t_order.user_id
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.merchant_id
     *
     * @return the value of t_order.merchant_id
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    public String getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.merchant_id
     *
     * @param merchantId the value for t_order.merchant_id
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    public void setMerchantId(String merchantId) {
        this.merchantId = merchantId == null ? null : merchantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.merchant_name
     *
     * @return the value of t_order.merchant_name
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    public String getMerchantName() {
        return merchantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.merchant_name
     *
     * @param merchantName the value for t_order.merchant_name
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    public void setMerchantName(String merchantName) {
        this.merchantName = merchantName == null ? null : merchantName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.ext_pay_order_no
     *
     * @return the value of t_order.ext_pay_order_no
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    public String getExtPayOrderNo() {
        return extPayOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.ext_pay_order_no
     *
     * @param extPayOrderNo the value for t_order.ext_pay_order_no
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    public void setExtPayOrderNo(String extPayOrderNo) {
        this.extPayOrderNo = extPayOrderNo == null ? null : extPayOrderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.ate_pay_order_no
     *
     * @return the value of t_order.ate_pay_order_no
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    public String getAtePayOrderNo() {
        return atePayOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.ate_pay_order_no
     *
     * @param atePayOrderNo the value for t_order.ate_pay_order_no
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    public void setAtePayOrderNo(String atePayOrderNo) {
        this.atePayOrderNo = atePayOrderNo == null ? null : atePayOrderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.pay_channel
     *
     * @return the value of t_order.pay_channel
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    public Integer getPayChannel() {
        return payChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.pay_channel
     *
     * @param payChannel the value for t_order.pay_channel
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    public void setPayChannel(Integer payChannel) {
        this.payChannel = payChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.pay_type
     *
     * @return the value of t_order.pay_type
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    public Integer getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.pay_type
     *
     * @param payType the value for t_order.pay_type
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    public void setPayType(Integer payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.pay_time
     *
     * @return the value of t_order.pay_time
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.pay_time
     *
     * @param payTime the value for t_order.pay_time
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.total_amount
     *
     * @return the value of t_order.total_amount
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    public Long getTotalAmount() {
        return totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.total_amount
     *
     * @param totalAmount the value for t_order.total_amount
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    public void setTotalAmount(Long totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.payable_amount
     *
     * @return the value of t_order.payable_amount
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    public Long getPayableAmount() {
        return payableAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.payable_amount
     *
     * @param payableAmount the value for t_order.payable_amount
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    public void setPayableAmount(Long payableAmount) {
        this.payableAmount = payableAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.paid_amount
     *
     * @return the value of t_order.paid_amount
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    public Long getPaidAmount() {
        return paidAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.paid_amount
     *
     * @param paidAmount the value for t_order.paid_amount
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    public void setPaidAmount(Long paidAmount) {
        this.paidAmount = paidAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.merchant_discount_amount
     *
     * @return the value of t_order.merchant_discount_amount
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    public Long getMerchantDiscountAmount() {
        return merchantDiscountAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.merchant_discount_amount
     *
     * @param merchantDiscountAmount the value for t_order.merchant_discount_amount
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    public void setMerchantDiscountAmount(Long merchantDiscountAmount) {
        this.merchantDiscountAmount = merchantDiscountAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.pay_discount_amount
     *
     * @return the value of t_order.pay_discount_amount
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    public Long getPayDiscountAmount() {
        return payDiscountAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.pay_discount_amount
     *
     * @param payDiscountAmount the value for t_order.pay_discount_amount
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    public void setPayDiscountAmount(Long payDiscountAmount) {
        this.payDiscountAmount = payDiscountAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.post_fee
     *
     * @return the value of t_order.post_fee
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    public Long getPostFee() {
        return postFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.post_fee
     *
     * @param postFee the value for t_order.post_fee
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    public void setPostFee(Long postFee) {
        this.postFee = postFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.buyer_message
     *
     * @return the value of t_order.buyer_message
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    public String getBuyerMessage() {
        return buyerMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.buyer_message
     *
     * @param buyerMessage the value for t_order.buyer_message
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    public void setBuyerMessage(String buyerMessage) {
        this.buyerMessage = buyerMessage == null ? null : buyerMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.seller_note
     *
     * @return the value of t_order.seller_note
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    public String getSellerNote() {
        return sellerNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.seller_note
     *
     * @param sellerNote the value for t_order.seller_note
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    public void setSellerNote(String sellerNote) {
        this.sellerNote = sellerNote == null ? null : sellerNote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.invoice_flag
     *
     * @return the value of t_order.invoice_flag
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    public Integer getInvoiceFlag() {
        return invoiceFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.invoice_flag
     *
     * @param invoiceFlag the value for t_order.invoice_flag
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    public void setInvoiceFlag(Integer invoiceFlag) {
        this.invoiceFlag = invoiceFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.status
     *
     * @return the value of t_order.status
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.status
     *
     * @param status the value for t_order.status
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.delete_flag
     *
     * @return the value of t_order.delete_flag
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    public Integer getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.delete_flag
     *
     * @param deleteFlag the value for t_order.delete_flag
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    public void setDeleteFlag(Integer deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.finish_time
     *
     * @return the value of t_order.finish_time
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    public Date getFinishTime() {
        return finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.finish_time
     *
     * @param finishTime the value for t_order.finish_time
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    public void setFinishTime(Date finishTime) {
        this.finishTime = finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.CREATE_TIME
     *
     * @return the value of t_order.CREATE_TIME
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.CREATE_TIME
     *
     * @param createTime the value for t_order.CREATE_TIME
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.UPDATE_TIME
     *
     * @return the value of t_order.UPDATE_TIME
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.UPDATE_TIME
     *
     * @param updateTime the value for t_order.UPDATE_TIME
     *
     * @mbg.generated Tue Jan 16 16:36:27 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}